/*
 * Hiarc API
 * Welcome to the Hiarc API documentation.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hiarcdb.client.api;

import com.hiarcdb.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AdminApi
 */
@Ignore
public class AdminApiTest {

    private final AdminApi api = new AdminApi();

    
    /**
     * Init the Hiarc database
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void initDBTest() throws ApiException {
        Object response = api.initDB();

        // TODO: test validations
    }
    
    /**
     * Reset the Hiarc database
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void resetDBTest() throws ApiException {
        Object response = api.resetDB();

        // TODO: test validations
    }
    
}
