/*
 * Hiarc API
 * Welcome to the Hiarc API documentation.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hiarcdb.client.api;

import com.hiarcdb.client.ApiException;
import com.hiarcdb.client.model.Classification;
import com.hiarcdb.client.model.CreateClassificationRequest;
import com.hiarcdb.client.model.CreateOrUpdateEntityRequest;
import com.hiarcdb.client.model.FindClassificationsRequest;
import com.hiarcdb.client.model.FindEntityRequest;
import com.hiarcdb.client.model.UpdateClassificationRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ClassificationApi
 */
@Ignore
public class ClassificationApiTest {

    private final ClassificationApi api = new ClassificationApi();

    
    /**
     * Create a Classification
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createClassificationTest() throws ApiException {
        CreateClassificationRequest createClassificationRequest = null;
        String xHiarcUserKey = null;
        Classification response = api.createClassification(createClassificationRequest, xHiarcUserKey);

        // TODO: test validations
    }
    
    /**
     * Delete a Classification
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteClassificationTest() throws ApiException {
        String key = null;
        String xHiarcUserKey = null;
        Object response = api.deleteClassification(key, xHiarcUserKey);

        // TODO: test validations
    }
    
    /**
     * Find a Classification
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findClassificationTest() throws ApiException {
        FindClassificationsRequest findClassificationsRequest = null;
        String xHiarcUserKey = null;
        List<Classification> response = api.findClassification(findClassificationsRequest, xHiarcUserKey);

        // TODO: test validations
    }
    
    /**
     * Get all Classifications
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllClassificationsTest() throws ApiException {
        String xHiarcUserKey = null;
        List<Classification> response = api.getAllClassifications(xHiarcUserKey);

        // TODO: test validations
    }
    
    /**
     * Get a Classification&#39;s Info
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getClassificationTest() throws ApiException {
        String key = null;
        String xHiarcUserKey = null;
        Classification response = api.getClassification(key, xHiarcUserKey);

        // TODO: test validations
    }
    
    /**
     * Update a Classification
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateClassificationTest() throws ApiException {
        String key = null;
        UpdateClassificationRequest updateClassificationRequest = null;
        String xHiarcUserKey = null;
        Classification response = api.updateClassification(key, updateClassificationRequest, xHiarcUserKey);

        // TODO: test validations
    }
    
}
