// /*
//  * Hiarc API
//  * Welcome to the Hiarc API documentation.
//  *
//  * The version of the OpenAPI document: 0.1.0
//  * 
//  *
//  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
//  * https://openapi-generator.tech
//  * Do not edit the class manually.
//  */


// package com.hiarcdb.client.api;

// import com.hiarcdb.client.ApiException;
// import com.hiarcdb.client.model.AddClassificationToFileRequest;
// import com.hiarcdb.client.model.AddGroupToFileRequest;
// import com.hiarcdb.client.model.AddRetentionPolicyToFileRequest;
// import com.hiarcdb.client.model.AddUserToFileRequest;
// import com.hiarcdb.client.model.AttachToExistingFileRequest;
// import com.hiarcdb.client.model.Collection;
// import com.hiarcdb.client.model.CopyFileRequest;
// import com.hiarcdb.client.model.CreateDirectUploadUrlRequest;
// import java.io.File;
// import com.hiarcdb.client.model.FileDirectDownload;
// import com.hiarcdb.client.model.FileDirectUpload;
// import com.hiarcdb.client.model.FileVersion;
// import com.hiarcdb.client.model.RetentionPolicyApplication;
// import com.hiarcdb.client.model.UpdateFileRequest;
// import org.junit.Test;
// import org.junit.Ignore;

// import java.util.ArrayList;
// import java.util.HashMap;
// import java.util.List;
// import java.util.Map;

// /**
//  * API tests for FileApi
//  */
// @Ignore
// public class FileApiTest {

//     private final FileApi api = new FileApi();

    
//     /**
//      * Add a Classification to a File
//      *
//      * 
//      *
//      * @throws ApiException
//      *          if the Api call fails
//      */
//     @Test
//     public void addClassificationToFileTest() throws ApiException {
//         String key = null;
//         AddClassificationToFileRequest addClassificationToFileRequest = null;
//         String xHiarcUserKey = null;
//         Object response = api.addClassificationToFile(key, addClassificationToFileRequest, xHiarcUserKey);

//         // TODO: test validations
//     }
    
//     /**
//      * Give a group access to a File
//      *
//      * 
//      *
//      * @throws ApiException
//      *          if the Api call fails
//      */
//     @Test
//     public void addGroupToFileTest() throws ApiException {
//         String key = null;
//         AddGroupToFileRequest addGroupToFileRequest = null;
//         String xHiarcUserKey = null;
//         Object response = api.addGroupToFile(key, addGroupToFileRequest, xHiarcUserKey);

//         // TODO: test validations
//     }
    
//     /**
//      * Add a Retention Policy to a File
//      *
//      * 
//      *
//      * @throws ApiException
//      *          if the Api call fails
//      */
//     @Test
//     public void addRetentionPolicyToFileTest() throws ApiException {
//         String key = null;
//         AddRetentionPolicyToFileRequest addRetentionPolicyToFileRequest = null;
//         String xHiarcUserKey = null;
//         Object response = api.addRetentionPolicyToFile(key, addRetentionPolicyToFileRequest, xHiarcUserKey);

//         // TODO: test validations
//     }
    
//     /**
//      * Give a user access to a File
//      *
//      * 
//      *
//      * @throws ApiException
//      *          if the Api call fails
//      */
//     @Test
//     public void addUserToFileTest() throws ApiException {
//         String key = null;
//         AddUserToFileRequest addUserToFileRequest = null;
//         String xHiarcUserKey = null;
//         Object response = api.addUserToFile(key, addUserToFileRequest, xHiarcUserKey);

//         // TODO: test validations
//     }
    
//     /**
//      * Add a new File Version
//      *
//      * 
//      *
//      * @throws ApiException
//      *          if the Api call fails
//      */
//     // @Test
//     // public void addVersionTest() throws ApiException {
//     //     String key = null;
//     //     String xHiarcUserKey = null;
//     //     String request = null;
//     //     File file = null;
//     //     java.io.File response = api.addVersion(key, xHiarcUserKey, request, file);

//     //     // TODO: test validations
//     // }
    
//     /**
//      * Attach to an existing File
//      *
//      * 
//      *
//      * @throws ApiException
//      *          if the Api call fails
//      */
//     @Test
//     public void attachToExisitingFileTest() throws ApiException {
//         String key = null;
//         AttachToExistingFileRequest attachToExistingFileRequest = null;
//         String xHiarcUserKey = null;
//         java.io.File response = api.attachToExisitingFile(key, attachToExistingFileRequest, xHiarcUserKey);

//         // TODO: test validations
//     }
    
//     /**
//      * Copy a File
//      *
//      * 
//      *
//      * @throws ApiException
//      *          if the Api call fails
//      */
//     @Test
//     public void copyFileTest() throws ApiException {
//         String key = null;
//         CopyFileRequest copyFileRequest = null;
//         String xHiarcUserKey = null;
//         java.io.File response = api.copyFile(key, copyFileRequest, xHiarcUserKey);

//         // TODO: test validations
//     }
    
//     /**
//      * Create a direct upload url to a storage service
//      *
//      * 
//      *
//      * @throws ApiException
//      *          if the Api call fails
//      */
//     @Test
//     public void createDirectUploadUrlTest() throws ApiException {
//         CreateDirectUploadUrlRequest createDirectUploadUrlRequest = null;
//         String xHiarcUserKey = null;
//         Integer expiresInSeconds = null;
//         FileDirectUpload response = api.createDirectUploadUrl(createDirectUploadUrlRequest, xHiarcUserKey, expiresInSeconds);

//         // TODO: test validations
//     }
    
//     /**
//      * Create a File
//      *
//      * 
//      *
//      * @throws ApiException
//      *          if the Api call fails
//      */
//     // @Test
//     // public void createFileTest() throws ApiException {
//     //     String xHiarcUserKey = null;
//     //     String request = null;
//     //     File file = null;
//     //     java.io.File response = api.createFile(xHiarcUserKey, request, file);

//     //     // TODO: test validations
//     // }
    
//     /**
//      * Delete a File
//      *
//      * 
//      *
//      * @throws ApiException
//      *          if the Api call fails
//      */
//     @Test
//     public void deleteFileTest() throws ApiException {
//         String key = null;
//         String xHiarcUserKey = null;
//         Object response = api.deleteFile(key, xHiarcUserKey);

//         // TODO: test validations
//     }
    
//     /**
//      * Download a File
//      *
//      * 
//      *
//      * @throws ApiException
//      *          if the Api call fails
//      */
//     // @Test
//     // public void downloadFileTest() throws ApiException {
//     //     String key = null;
//     //     String xHiarcUserKey = null;
//     //     File response = api.downloadFile(key, xHiarcUserKey);

//     //     // TODO: test validations
//     // }
    
//     /**
//      * Get a list of Collections for a File
//      *
//      * 
//      *
//      * @throws ApiException
//      *          if the Api call fails
//      */
//     @Test
//     public void getCollectionsForFileTest() throws ApiException {
//         String key = null;
//         String xHiarcUserKey = null;
//         List<Collection> response = api.getCollectionsForFile(key, xHiarcUserKey);

//         // TODO: test validations
//     }
    
//     /**
//      * Get a direct download URL to a File
//      *
//      * 
//      *
//      * @throws ApiException
//      *          if the Api call fails
//      */
//     @Test
//     public void getDirectDownloadUrlTest() throws ApiException {
//         String key = null;
//         String xHiarcUserKey = null;
//         Integer expiresInSeconds = null;
//         FileDirectDownload response = api.getDirectDownloadUrl(key, xHiarcUserKey, expiresInSeconds);

//         // TODO: test validations
//     }
    
//     /**
//      * Get a File&#39;s Info
//      *
//      * 
//      *
//      * @throws ApiException
//      *          if the Api call fails
//      */
//     @Test
//     public void getFileTest() throws ApiException {
//         String key = null;
//         String xHiarcUserKey = null;
//         java.io.File response = api.getFile(key, xHiarcUserKey);

//         // TODO: test validations
//     }
    
//     /**
//      * Get a list of Retention Policies on a File
//      *
//      * 
//      *
//      * @throws ApiException
//      *          if the Api call fails
//      */
//     @Test
//     public void getRetentionPoliciesTest() throws ApiException {
//         String key = null;
//         String xHiarcUserKey = null;
//         List<RetentionPolicyApplication> response = api.getRetentionPolicies(key, xHiarcUserKey);

//         // TODO: test validations
//     }
    
//     /**
//      * Get a list of File Versions
//      *
//      * 
//      *
//      * @throws ApiException
//      *          if the Api call fails
//      */
//     @Test
//     public void getVersionsTest() throws ApiException {
//         String key = null;
//         String xHiarcUserKey = null;
//         List<FileVersion> response = api.getVersions(key, xHiarcUserKey);

//         // TODO: test validations
//     }
    
//     /**
//      * Update a File
//      *
//      * 
//      *
//      * @throws ApiException
//      *          if the Api call fails
//      */
//     @Test
//     public void updateFileTest() throws ApiException {
//         String key = null;
//         UpdateFileRequest updateFileRequest = null;
//         java.io.File response = api.updateFile(key, updateFileRequest);

//         // TODO: test validations
//     }
    // /**
    //  * Filter a list of File keys that a User can access
    //  *
    //  * 
    //  *
    //  * @throws ApiException
    //  *          if the Api call fails
    //  */
    // @Test
    // public void filterAllowedFilesTest() throws ApiException {
    //     AllowedFilesRequest allowedFilesRequest = null;
    //     String xHiarcUserKey = null;
    //     List<String> response = api.filterAllowedFiles(allowedFilesRequest, xHiarcUserKey);

    //     // TODO: test validations
    // }
// }
