/*
 * Hiarc API
 * Welcome to the Hiarc API documentation.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hiarcdb.client.api;

import com.hiarcdb.client.ApiException;
import com.hiarcdb.client.model.CreateGroupRequest;
import com.hiarcdb.client.model.CreateOrUpdateEntityRequest;
import com.hiarcdb.client.model.FindEntityRequest;
import com.hiarcdb.client.model.FindGroupsRequest;
import com.hiarcdb.client.model.Group;
import com.hiarcdb.client.model.UpdateGroupRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GroupApi
 */
@Ignore
public class GroupApiTest {

    private final GroupApi api = new GroupApi();

    
    /**
     * Add a User to a Group
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addUserToGroupTest() throws ApiException {
        String key = null;
        String userKey = null;
        Object response = api.addUserToGroup(key, userKey);

        // TODO: test validations
    }
    
    /**
     * Create a Group
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createGroupTest() throws ApiException {
        CreateGroupRequest createGroupRequest = null;
        Group response = api.createGroup(createGroupRequest);

        // TODO: test validations
    }
    
    /**
     * Delete a Group
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteGroupTest() throws ApiException {
        String key = null;
        Object response = api.deleteGroup(key);

        // TODO: test validations
    }
    
    /**
     * Find a Group
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findGroupTest() throws ApiException {
        FindGroupsRequest findGroupsRequest = null;
        List<Group> response = api.findGroup(findGroupsRequest);

        // TODO: test validations
    }
    
    /**
     * Get all Groups
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllGroupsTest() throws ApiException {
        List<Group> response = api.getAllGroups();

        // TODO: test validations
    }
    
    /**
     * Get a Group&#39;s Info
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getGroupTest() throws ApiException {
        String key = null;
        Group response = api.getGroup(key);

        // TODO: test validations
    }
    
    /**
     * Get the Groups for the current User
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getGroupsForCurrentUserTest() throws ApiException {
        String xHiarcUserKey = null;
        List<Group> response = api.getGroupsForCurrentUser(xHiarcUserKey);

        // TODO: test validations
    }
    
    /**
     * Update a Group
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateGroupTest() throws ApiException {
        String key = null;
        UpdateGroupRequest updateGroupRequest = null;
        Group response = api.updateGroup(key, updateGroupRequest);

        // TODO: test validations
    }
    
}
