/*
 * Hiarc API
 * Welcome to the Hiarc API documentation.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hiarcdb.client.api;

import com.hiarcdb.client.ApiException;
import com.hiarcdb.client.model.CreateLegalHoldRequest;
import com.hiarcdb.client.model.CreateOrUpdateEntityRequest;
import com.hiarcdb.client.model.LegalHold;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LegalHoldApi
 */
@Ignore
public class LegalHoldApiTest {

    private final LegalHoldApi api = new LegalHoldApi();

    
    /**
     * Create a Legal Hold
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createLegalHoldTest() throws ApiException {
        CreateLegalHoldRequest createLegalHoldRequest = null;
        LegalHold response = api.createLegalHold(createLegalHoldRequest);

        // TODO: test validations
    }
    
    /**
     * Get a Legal Hold&#39;s Info
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getLegalHoldTest() throws ApiException {
        String key = null;
        LegalHold response = api.getLegalHold(key);

        // TODO: test validations
    }
    
}
