/*
 * Hiarc API
 * Welcome to the Hiarc API documentation.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hiarcdb.client.api;

import com.hiarcdb.client.ApiException;
import com.hiarcdb.client.model.CreateRetentionPolicyRequest;
import com.hiarcdb.client.model.FindEntityRequest;
import com.hiarcdb.client.model.FindRetentionPoliciesRequest;
import com.hiarcdb.client.model.RetentionPolicy;
import com.hiarcdb.client.model.UpdateRetentionPolicyRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RetentionPolicyApi
 */
@Ignore
public class RetentionPolicyApiTest {

    private final RetentionPolicyApi api = new RetentionPolicyApi();

    
    /**
     * Create a Retention Policy
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createRetentionPolicyTest() throws ApiException {
        CreateRetentionPolicyRequest createRetentionPolicyRequest = null;
        RetentionPolicy response = api.createRetentionPolicy(createRetentionPolicyRequest);

        // TODO: test validations
    }
    
    /**
     * Find a Retention Policy
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findRetentionPoliciesTest() throws ApiException {
        FindRetentionPoliciesRequest findRetentionPoliciesRequest = null;
        List<RetentionPolicy> response = api.findRetentionPolicies(findRetentionPoliciesRequest);

        // TODO: test validations
    }
    
    /**
     * Get all Retention Policies
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllRetentionPoliciesTest() throws ApiException {
        List<RetentionPolicy> response = api.getAllRetentionPolicies();

        // TODO: test validations
    }
    
    /**
     * Get a Retention Policy&#39;s Info
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRetentionPolicyTest() throws ApiException {
        String key = null;
        RetentionPolicy response = api.getRetentionPolicy(key);

        // TODO: test validations
    }
    
    /**
     * Update a Retention Policy
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateRetentionPolicyTest() throws ApiException {
        String key = null;
        UpdateRetentionPolicyRequest updateRetentionPolicyRequest = null;
        RetentionPolicy response = api.updateRetentionPolicy(key, updateRetentionPolicyRequest);

        // TODO: test validations
    }
    
}
