/*
 * Hiarc API
 * Welcome to the Hiarc API documentation.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hiarcdb.client.api;

import com.hiarcdb.client.ApiCallback;
import com.hiarcdb.client.ApiClient;
import com.hiarcdb.client.ApiException;
import com.hiarcdb.client.ApiResponse;
import com.hiarcdb.client.Configuration;
import com.hiarcdb.client.Pair;
import com.hiarcdb.client.ProgressRequestBody;
import com.hiarcdb.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.hiarcdb.client.model.CreateRetentionPolicyRequest;
import com.hiarcdb.client.model.FindEntityRequest;
import com.hiarcdb.client.model.FindRetentionPoliciesRequest;
import com.hiarcdb.client.model.RetentionPolicy;
import com.hiarcdb.client.model.UpdateRetentionPolicyRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class RetentionPolicyApi {
    private ApiClient localVarApiClient;

    public RetentionPolicyApi() {
        this(Configuration.getDefaultApiClient());
    }

    public RetentionPolicyApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    /**
     * Build call for createRetentionPolicy
     * @param createRetentionPolicyRequest Retention Policy information (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> A Retention Policy object </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createRetentionPolicyCall(CreateRetentionPolicyRequest createRetentionPolicyRequest, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = createRetentionPolicyRequest;

        // create path and map variables
        String localVarPath = "/retentionpolicies";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();
        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "AdminApiKeyAuth" };
        return localVarApiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createRetentionPolicyValidateBeforeCall(CreateRetentionPolicyRequest createRetentionPolicyRequest, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'createRetentionPolicyRequest' is set
        if (createRetentionPolicyRequest == null) {
            throw new ApiException("Missing the required parameter 'createRetentionPolicyRequest' when calling createRetentionPolicy(Async)");
        }
        

        okhttp3.Call localVarCall = createRetentionPolicyCall(createRetentionPolicyRequest, _callback);
        return localVarCall;

    }

    /**
     * Create a Retention Policy
     * 
     * @param createRetentionPolicyRequest Retention Policy information (required)
     * @return RetentionPolicy
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> A Retention Policy object </td><td>  -  </td></tr>
     </table>
     */
    public RetentionPolicy createRetentionPolicy(CreateRetentionPolicyRequest createRetentionPolicyRequest) throws ApiException {
        ApiResponse<RetentionPolicy> localVarResp = createRetentionPolicyWithHttpInfo(createRetentionPolicyRequest);
        return localVarResp.getData();
    }

    /**
     * Create a Retention Policy
     * 
     * @param createRetentionPolicyRequest Retention Policy information (required)
     * @return ApiResponse&lt;RetentionPolicy&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> A Retention Policy object </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<RetentionPolicy> createRetentionPolicyWithHttpInfo(CreateRetentionPolicyRequest createRetentionPolicyRequest) throws ApiException {
        okhttp3.Call localVarCall = createRetentionPolicyValidateBeforeCall(createRetentionPolicyRequest, null);
        Type localVarReturnType = new TypeToken<RetentionPolicy>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create a Retention Policy (asynchronously)
     * 
     * @param createRetentionPolicyRequest Retention Policy information (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> A Retention Policy object </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createRetentionPolicyAsync(CreateRetentionPolicyRequest createRetentionPolicyRequest, final ApiCallback<RetentionPolicy> _callback) throws ApiException {

        okhttp3.Call localVarCall = createRetentionPolicyValidateBeforeCall(createRetentionPolicyRequest, _callback);
        Type localVarReturnType = new TypeToken<RetentionPolicy>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for findRetentionPolicies
     * @param findRetentionPoliciesRequest Retention Policy query (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of Retention Policy objects </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call findRetentionPoliciesCall(FindRetentionPoliciesRequest findRetentionPoliciesRequest, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = findRetentionPoliciesRequest;

        // create path and map variables
        String localVarPath = "/retentionpolicies/find";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();
        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "AdminApiKeyAuth" };
        return localVarApiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call findRetentionPoliciesValidateBeforeCall(FindRetentionPoliciesRequest findRetentionPoliciesRequest, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'findRetentionPoliciesRequest' is set
        if (findRetentionPoliciesRequest == null) {
            throw new ApiException("Missing the required parameter 'findRetentionPoliciesRequest' when calling findRetentionPolicies(Async)");
        }
        

        okhttp3.Call localVarCall = findRetentionPoliciesCall(findRetentionPoliciesRequest, _callback);
        return localVarCall;

    }

    /**
     * Find a Retention Policy
     * 
     * @param findRetentionPoliciesRequest Retention Policy query (required)
     * @return List&lt;RetentionPolicy&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of Retention Policy objects </td><td>  -  </td></tr>
     </table>
     */
    public List<RetentionPolicy> findRetentionPolicies(FindRetentionPoliciesRequest findRetentionPoliciesRequest) throws ApiException {
        ApiResponse<List<RetentionPolicy>> localVarResp = findRetentionPoliciesWithHttpInfo(findRetentionPoliciesRequest);
        return localVarResp.getData();
    }

    /**
     * Find a Retention Policy
     * 
     * @param findRetentionPoliciesRequest Retention Policy query (required)
     * @return ApiResponse&lt;List&lt;RetentionPolicy&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of Retention Policy objects </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<RetentionPolicy>> findRetentionPoliciesWithHttpInfo(FindRetentionPoliciesRequest findRetentionPoliciesRequest) throws ApiException {
        okhttp3.Call localVarCall = findRetentionPoliciesValidateBeforeCall(findRetentionPoliciesRequest, null);
        Type localVarReturnType = new TypeToken<List<RetentionPolicy>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Find a Retention Policy (asynchronously)
     * 
     * @param findRetentionPoliciesRequest Retention Policy query (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of Retention Policy objects </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call findRetentionPoliciesAsync(FindRetentionPoliciesRequest findRetentionPoliciesRequest, final ApiCallback<List<RetentionPolicy>> _callback) throws ApiException {

        okhttp3.Call localVarCall = findRetentionPoliciesValidateBeforeCall(findRetentionPoliciesRequest, _callback);
        Type localVarReturnType = new TypeToken<List<RetentionPolicy>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getAllRetentionPolicies
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of Retention Policy objects </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAllRetentionPoliciesCall(final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/retentionpolicies";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();
        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "AdminApiKeyAuth" };
        return localVarApiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getAllRetentionPoliciesValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        

        okhttp3.Call localVarCall = getAllRetentionPoliciesCall(_callback);
        return localVarCall;

    }

    /**
     * Get all Retention Policies
     * 
     * @return List&lt;RetentionPolicy&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of Retention Policy objects </td><td>  -  </td></tr>
     </table>
     */
    public List<RetentionPolicy> getAllRetentionPolicies() throws ApiException {
        ApiResponse<List<RetentionPolicy>> localVarResp = getAllRetentionPoliciesWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Get all Retention Policies
     * 
     * @return ApiResponse&lt;List&lt;RetentionPolicy&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of Retention Policy objects </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<RetentionPolicy>> getAllRetentionPoliciesWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = getAllRetentionPoliciesValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<List<RetentionPolicy>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get all Retention Policies (asynchronously)
     * 
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of Retention Policy objects </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAllRetentionPoliciesAsync(final ApiCallback<List<RetentionPolicy>> _callback) throws ApiException {

        okhttp3.Call localVarCall = getAllRetentionPoliciesValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<List<RetentionPolicy>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getRetentionPolicy
     * @param key Key of Retention Policy to get info (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A Retention Policy object </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getRetentionPolicyCall(String key, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/retentionpolicies/{key}"
            .replaceAll("\\{" + "key" + "\\}", localVarApiClient.escapeString(key.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();
        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "AdminApiKeyAuth" };
        return localVarApiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getRetentionPolicyValidateBeforeCall(String key, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'key' is set
        if (key == null) {
            throw new ApiException("Missing the required parameter 'key' when calling getRetentionPolicy(Async)");
        }
        

        okhttp3.Call localVarCall = getRetentionPolicyCall(key, _callback);
        return localVarCall;

    }

    /**
     * Get a Retention Policy&#39;s Info
     * 
     * @param key Key of Retention Policy to get info (required)
     * @return RetentionPolicy
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A Retention Policy object </td><td>  -  </td></tr>
     </table>
     */
    public RetentionPolicy getRetentionPolicy(String key) throws ApiException {
        ApiResponse<RetentionPolicy> localVarResp = getRetentionPolicyWithHttpInfo(key);
        return localVarResp.getData();
    }

    /**
     * Get a Retention Policy&#39;s Info
     * 
     * @param key Key of Retention Policy to get info (required)
     * @return ApiResponse&lt;RetentionPolicy&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A Retention Policy object </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<RetentionPolicy> getRetentionPolicyWithHttpInfo(String key) throws ApiException {
        okhttp3.Call localVarCall = getRetentionPolicyValidateBeforeCall(key, null);
        Type localVarReturnType = new TypeToken<RetentionPolicy>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get a Retention Policy&#39;s Info (asynchronously)
     * 
     * @param key Key of Retention Policy to get info (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A Retention Policy object </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getRetentionPolicyAsync(String key, final ApiCallback<RetentionPolicy> _callback) throws ApiException {

        okhttp3.Call localVarCall = getRetentionPolicyValidateBeforeCall(key, _callback);
        Type localVarReturnType = new TypeToken<RetentionPolicy>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateRetentionPolicy
     * @param key Key of Retention Policy to update (required)
     * @param updateRetentionPolicyRequest RetentionPolicy information (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A Retention Policy object </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateRetentionPolicyCall(String key, UpdateRetentionPolicyRequest updateRetentionPolicyRequest, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = updateRetentionPolicyRequest;

        // create path and map variables
        String localVarPath = "/retentionpolicies/{key}"
            .replaceAll("\\{" + "key" + "\\}", localVarApiClient.escapeString(key.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();
        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "AdminApiKeyAuth" };
        return localVarApiClient.buildCall(localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateRetentionPolicyValidateBeforeCall(String key, UpdateRetentionPolicyRequest updateRetentionPolicyRequest, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'key' is set
        if (key == null) {
            throw new ApiException("Missing the required parameter 'key' when calling updateRetentionPolicy(Async)");
        }
        
        // verify the required parameter 'updateRetentionPolicyRequest' is set
        if (updateRetentionPolicyRequest == null) {
            throw new ApiException("Missing the required parameter 'updateRetentionPolicyRequest' when calling updateRetentionPolicy(Async)");
        }
        

        okhttp3.Call localVarCall = updateRetentionPolicyCall(key, updateRetentionPolicyRequest, _callback);
        return localVarCall;

    }

    /**
     * Update a Retention Policy
     * 
     * @param key Key of Retention Policy to update (required)
     * @param updateRetentionPolicyRequest RetentionPolicy information (required)
     * @return RetentionPolicy
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A Retention Policy object </td><td>  -  </td></tr>
     </table>
     */
    public RetentionPolicy updateRetentionPolicy(String key, UpdateRetentionPolicyRequest updateRetentionPolicyRequest) throws ApiException {
        ApiResponse<RetentionPolicy> localVarResp = updateRetentionPolicyWithHttpInfo(key, updateRetentionPolicyRequest);
        return localVarResp.getData();
    }

    /**
     * Update a Retention Policy
     * 
     * @param key Key of Retention Policy to update (required)
     * @param updateRetentionPolicyRequest RetentionPolicy information (required)
     * @return ApiResponse&lt;RetentionPolicy&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A Retention Policy object </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<RetentionPolicy> updateRetentionPolicyWithHttpInfo(String key, UpdateRetentionPolicyRequest updateRetentionPolicyRequest) throws ApiException {
        okhttp3.Call localVarCall = updateRetentionPolicyValidateBeforeCall(key, updateRetentionPolicyRequest, null);
        Type localVarReturnType = new TypeToken<RetentionPolicy>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update a Retention Policy (asynchronously)
     * 
     * @param key Key of Retention Policy to update (required)
     * @param updateRetentionPolicyRequest RetentionPolicy information (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A Retention Policy object </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateRetentionPolicyAsync(String key, UpdateRetentionPolicyRequest updateRetentionPolicyRequest, final ApiCallback<RetentionPolicy> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateRetentionPolicyValidateBeforeCall(key, updateRetentionPolicyRequest, _callback);
        Type localVarReturnType = new TypeToken<RetentionPolicy>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
