/*
 * Hiarc API
 * Welcome to the Hiarc API documentation.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hiarcdb.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AddFileToCollectionRequest
 */
public class AddFileToCollectionRequestTest {
    private final AddFileToCollectionRequest model = new AddFileToCollectionRequest();

    /**
     * Model tests for AddFileToCollectionRequest
     */
    @Test
    public void testAddFileToCollectionRequest() {
        // TODO: test AddFileToCollectionRequest
    }

    /**
     * Test the property 'fileKey'
     */
    @Test
    public void fileKeyTest() {
        // TODO: test fileKey
    }

}
