/*
 * Hiarc API
 * Welcome to the Hiarc API documentation.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hiarcdb.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.hiarcdb.client.model.AccessLevel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AddGroupToCollectionRequest
 */
public class AddGroupToCollectionRequestTest {
    private final AddGroupToCollectionRequest model = new AddGroupToCollectionRequest();

    /**
     * Model tests for AddGroupToCollectionRequest
     */
    @Test
    public void testAddGroupToCollectionRequest() {
        // TODO: test AddGroupToCollectionRequest
    }

    /**
     * Test the property 'groupKey'
     */
    @Test
    public void groupKeyTest() {
        // TODO: test groupKey
    }

    /**
     * Test the property 'accessLevel'
     */
    @Test
    public void accessLevelTest() {
        // TODO: test accessLevel
    }

}
