/*
 * Hiarc API
 * Welcome to the Hiarc API documentation.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hiarcdb.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.hiarcdb.client.model.RetentionPolicy;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for RetentionPolicyApplication
 */
public class RetentionPolicyApplicationTest {
    private final RetentionPolicyApplication model = new RetentionPolicyApplication();

    /**
     * Model tests for RetentionPolicyApplication
     */
    @Test
    public void testRetentionPolicyApplication() {
        // TODO: test RetentionPolicyApplication
    }

    /**
     * Test the property 'retentionPolicy'
     */
    @Test
    public void retentionPolicyTest() {
        // TODO: test retentionPolicy
    }

    /**
     * Test the property 'appliedAt'
     */
    @Test
    public void appliedAtTest() {
        // TODO: test appliedAt
    }

    /**
     * Test the property 'expiresAt'
     */
    @Test
    public void expiresAtTest() {
        // TODO: test expiresAt
    }

}
