/*
 * Hiarc API
 * Welcome to the Hiarc API documentation.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hiarcdb.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for UserCredentials
 */
public class UserCredentialsTest {
    private final UserCredentials model = new UserCredentials();

    /**
     * Model tests for UserCredentials
     */
    @Test
    public void testUserCredentials() {
        // TODO: test UserCredentials
    }

    /**
     * Test the property 'userKey'
     */
    @Test
    public void userKeyTest() {
        // TODO: test userKey
    }

    /**
     * Test the property 'bearerToken'
     */
    @Test
    public void bearerTokenTest() {
        // TODO: test bearerToken
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'expiresAt'
     */
    @Test
    public void expiresAtTest() {
        // TODO: test expiresAt
    }

}
