/*
 * Hiarc API
 * Welcome to the Hiarc API documentation.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hiarcdb.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets AccessLevel
 */
@JsonAdapter(AccessLevel.Adapter.class)
public enum AccessLevel {
  
  CO_OWNER("CO_OWNER"),
  
  READ_WRITE("READ_WRITE"),
  
  READ_ONLY("READ_ONLY"),
  
  UPLOAD_ONLY("UPLOAD_ONLY");

  private String value;

  AccessLevel(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static AccessLevel fromValue(String value) {
    for (AccessLevel b : AccessLevel.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<AccessLevel> {
    @Override
    public void write(final JsonWriter jsonWriter, final AccessLevel enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public AccessLevel read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return AccessLevel.fromValue(value);
    }
  }
}

