/*
 * Hiarc API
 * Welcome to the Hiarc API documentation.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hiarcdb.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * AddRetentionPolicyToFileRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-12-01T01:09:47.879763-06:00[America/Chicago]")
public class AddRetentionPolicyToFileRequest {
  public static final String SERIALIZED_NAME_RETENTION_POLICY_KEY = "retentionPolicyKey";
  @SerializedName(SERIALIZED_NAME_RETENTION_POLICY_KEY)
  private String retentionPolicyKey;


  public AddRetentionPolicyToFileRequest retentionPolicyKey(String retentionPolicyKey) {
    
    this.retentionPolicyKey = retentionPolicyKey;
    return this;
  }

   /**
   * Get retentionPolicyKey
   * @return retentionPolicyKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRetentionPolicyKey() {
    return retentionPolicyKey;
  }


  public void setRetentionPolicyKey(String retentionPolicyKey) {
    this.retentionPolicyKey = retentionPolicyKey;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddRetentionPolicyToFileRequest addRetentionPolicyToFileRequest = (AddRetentionPolicyToFileRequest) o;
    return Objects.equals(this.retentionPolicyKey, addRetentionPolicyToFileRequest.retentionPolicyKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(retentionPolicyKey);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddRetentionPolicyToFileRequest {\n");
    sb.append("    retentionPolicyKey: ").append(toIndentedString(retentionPolicyKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

