/*
 * Hiarc API
 * Welcome to the Hiarc API documentation.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hiarcdb.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * FileDirectDownload
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-12-01T01:09:47.879763-06:00[America/Chicago]")
public class FileDirectDownload {
  public static final String SERIALIZED_NAME_KEY = "key";
  @SerializedName(SERIALIZED_NAME_KEY)
  private String key;

  public static final String SERIALIZED_NAME_DIRECT_DOWNLOAD_URL = "directDownloadUrl";
  @SerializedName(SERIALIZED_NAME_DIRECT_DOWNLOAD_URL)
  private String directDownloadUrl;

  public static final String SERIALIZED_NAME_EXPIRES_AT = "expiresAt";
  @SerializedName(SERIALIZED_NAME_EXPIRES_AT)
  private OffsetDateTime expiresAt;


  public FileDirectDownload key(String key) {
    
    this.key = key;
    return this;
  }

   /**
   * Get key
   * @return key
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getKey() {
    return key;
  }


  public void setKey(String key) {
    this.key = key;
  }


  public FileDirectDownload directDownloadUrl(String directDownloadUrl) {
    
    this.directDownloadUrl = directDownloadUrl;
    return this;
  }

   /**
   * Get directDownloadUrl
   * @return directDownloadUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDirectDownloadUrl() {
    return directDownloadUrl;
  }


  public void setDirectDownloadUrl(String directDownloadUrl) {
    this.directDownloadUrl = directDownloadUrl;
  }


  public FileDirectDownload expiresAt(OffsetDateTime expiresAt) {
    
    this.expiresAt = expiresAt;
    return this;
  }

   /**
   * Get expiresAt
   * @return expiresAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getExpiresAt() {
    return expiresAt;
  }


  public void setExpiresAt(OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FileDirectDownload fileDirectDownload = (FileDirectDownload) o;
    return Objects.equals(this.key, fileDirectDownload.key) &&
        Objects.equals(this.directDownloadUrl, fileDirectDownload.directDownloadUrl) &&
        Objects.equals(this.expiresAt, fileDirectDownload.expiresAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(key, directDownloadUrl, expiresAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FileDirectDownload {\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    directDownloadUrl: ").append(toIndentedString(directDownloadUrl)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

